services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    image: safaj/mern-server:5
    container_name: mern-server
    ports:
      - "9000:9000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/todos
      - PORT=9000
    depends_on:
      - mongo

  client:
    image: safaj/mern-client:5
    container_name: mern-client
    ports:
      - "3000:80"
    depends_on:
      - server

volumes:
  mongo-data:
